name: Build OCI Images

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_type: pulp_fedora31
            test_image: pulp-fedora31
          - test_type: pulp_galaxy_ng
            test_image: pulp-galaxy-ng
          - test_type: pulp
            test_image: pulp
    steps:
      - uses: actions/checkout@v2
      - name: Build the images
        run: |
          wget https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
          docker build --file pulp_ci/Containerfile --tag pulp/pulp-ci:latest .
          docker build --file pulp_ci_centos/Containerfile --tag pulp/pulp-ci-centos:latest .
          docker build --file ${{ matrix.test_type }}/Containerfile --tag pulp/${{ matrix.test_image }}:latest .
      - name: Test the images
        run: |
          mkdir settings
          echo "CONTENT_ORIGIN='http://$(hostname):8080'" >> settings/settings.py
          docker run --detach \
                     --name pulp \
                     --publish 8080:80 \
                     --volume "/$(pwd)/settings:/etc/pulp:Z" \
                     --device /dev/fuse \
                     pulp/${{ matrix.test_image }}:latest
          sleep 10
          for _ in $(seq 10)
          do
            sleep 3
            if curl --fail http://localhost:8080/pulp/api/v3/status/ > /dev/null 2>&1
            then
              echo "SUCCESS."
              break
            fi
          done
          curl --fail http://localhost:8080/pulp/api/v3/status/
      - name: Display log on error
        if: failure()
        run: docker logs pulp
